### ISSUE TITLE
generateAuthUrl

### ISSUE THREAD

**Issue by ilrein** [lpinca/shopify-token#10]
I am not sure if this works as intended after the application is already installed, since it automatically injects myshopify.com

``` 
return url.format({
      pathname: '/admin/oauth/authorize',
      hostname: `${shop}.myshopify.com`,
      protocol: 'https:',
      query
    });
```

My first round was fine, but after the app is installed and the link is present in the user's dashboard, I think it keeps adding myshopify.com resulting in some wonky urls like: 

```made2measure-example.myshopify.com.myshopify.com```

It actually took me a couple of hours to finally address this, which I did with:

```
if (uri.match(/.myshopify.com/gi).length > 0) {
      uri.replace('.myshopify.com', '')
    }
```

**Comment by lpinca** [comment]
That can only happen if you use `made2measure-example.myshopify.com` as shop name which is wrong.

**Comment by ilrein** [comment]
So is the right strategy to make sure you never have ```myshopify.com``` attached to the shop name parameter?

**Comment by lpinca** [comment]
Yes, you should not invoke that method with an invalid shop name or it will produce an invalid URL :)
