### ISSUE TITLE
redirectUri is required

### ISSUE THREAD

**Issue by babenzele** [lpinca/shopify-token#11]
If I only need to `verifyHmac`, why is `redirectUri` required?

**Comment by lpinca** [comment]
Because `verifyHmac` is an instance method. It wasn't designed to be used as a standalone function.
You can still do that though, something like this should work:

```js
ShopifyToken.prototype.verifyHmac.call({ sharedSecret }, query);
```

**Comment by babenzele** [comment]
Ah, that makes sense to call it directly. Thanks for the tip. 

Getting lots of use out of this and the api lib, thanks a ton.
