### ISSUE TITLE
Can generateAuthUrl use a myshopify domain instead of the shop name

### ISSUE THREAD

**Issue by mozeryansky** [lpinca/shopify-token#14]
Based on the spec from [https://help.shopify.com/en/api/getting-started/authentication/oauth#update-oauth-scopes](https://help.shopify.com/en/api/getting-started/authentication/oauth#update-oauth-scopes), the auth url should be "the users myshopify domain".

However, the `generateAuthUrl` function appends ".myshopify.com". So during the authentication flow that Shopify describes they will send the myshopify domain. Then I have to remove the ".myshopify.com" from that parameter to be able to pass it to `generateAuthUrl` to work properly.

Can this be fixed? How do you use `generateAuthUrl`?

**Comment by lpinca** [comment]
`shop` is the shop name without the `.myshopify.com` suffix.

**Comment by mozeryansky** [comment]
Yes I know. But the query parameter that Shopify sends is the full shop domain. So I have to remove the ".myshopify.com" suffix. To get the shop name. Then I pass that shop name like this: `generateAuthUrl(shop)`, and this function appends back ".myshopify.com". 

Instead of me needing to remove the suffix. Can then `generateAuthUrl` function allow full domains? Maybe it can do both by just checking if the ".myshopify.com" suffix exists or not.

**Comment by lpinca** [comment]
I'm not sure why you rely on a search parameter sent by Shopify. Can you elaborate? What's the flow? As far as I know Shopify send the hostname of the user's shop when it's time to exchange the authorization code for a permanent access token e.g. when it send a request to the "callback" endpoint. Are you using `generateAuthUrl()` as this stage? If so why?

With that said yes we could change this line

https://github.com/lpinca/shopify-token/blob/06880b1eb65e4358f75a8923d7fea357609bbbe0/index.js#L89

to 

```js
hostname: shop.endsWith('.myshopify.com') ? shop : `${shop}.myshopify.com`
```

**Comment by mozeryansky** [comment]
I am following step #1 of the OAuth Authentication Flow: [https://help.shopify.com/en/api/getting-started/authentication/oauth#step-2-ask-for-permission](https://help.shopify.com/en/api/getting-started/authentication/oauth#step-2-ask-for-permission).

The instructions say Shopify will send a GET request to my server. In that query the shop parameter is a myshopify domain. I verify the hmac of that query to ensure it's valid and from Shopify. Next, it says to "redirect the user to the following URL..." which is "{shop}.myshopify.com".

So since I can trust the query parameters I would like to pass them directly to `generateAuthUrl()`. But I need to first remove the suffix. The solution you provided is perfect!

**Comment by lpinca** [comment]
Fixed in https://github.com/lpinca/shopify-token/commit/33833769d33ff0872702beffce4d0afd8560660e and published in version 3.0.3

**Comment by mozeryansky** [comment]
Awesome! I've already updated my local package and tested it out. Thank you.

**Comment by mozeryansky** [comment]
It looks like someone else reported this way before me on Nov 19, 2017: https://github.com/lpinca/shopify-token/issues/10
