### ISSUE TITLE
Anyway to pass metafields?

### ISSUE THREAD

**Issue by junaid33** [lpinca/shopify-token#26]
So we use wildcard domains: junaid.myapp.com. Every user gets a specific domain and can add multiple Shopify shops to their account. The issue is each redirect URL will be different. Can we send the subdomain as a metafield during oAuth and get Shopify to send it back during the callback? That way, we can have one redirect URL where we get the shop, accessToken, and the subdomain we sent during the initial call. 

I also tried adding wildcard domains on the app settings page: *.myapp.com but seems like wildcards do not work.

**Comment by lpinca** [comment]
No, this is not supported. See https://shopify.dev/tutorials/authenticate-with-oauth

**Comment by junaid33** [comment]
OK so I think best way would be to save subdomain and shop to a database when the user wants to add a shop. Check that DB during the callback function and redirect. Appreciate all the work you put into this package.
