### ISSUE TITLE
Bug with `encodeKey` and `encodeValue`

### ISSUE THREAD

**Issue by benbuckman** [lpinca/shopify-token#3]
`encodeValue` looks like this (https://github.com/lpinca/shopify-token/blob/master/index.js#L7-L29)

```js
function encodeValue(input) {
  return input.replace(/&/g, '%26').replace(/%/g, '%25');
}
```

If `input` was `'&'`, it would return `'%2526'` – the `%` from the first `replace` is replaced again in the 2nd one.

Is there a reason not to use use `encodeURIComponent`?
Or perhaps,

```js
input.replace(/[&%]/g, function(c) { return encodeURIComponent(c); })
```

?

Thanks

**Comment by lpinca** [comment]
This looks indeed like a bug, good catch.
Something like this:
```js
function encodeValue(input) {
  return s.replace(/[&%]/g, function (c) {
    return c === '&' ? '%26' : '%25';
  });
}
```
should work.

**Comment by lpinca** [comment]
I'm not using `encodeURIComponent` directly due to this specification:

> The characters & and % are replaced with %26 and %25 respectively in keys and values. Additionally the = character is replaced with %3D in keys.

**Comment by benbuckman** [comment]
I don't think those docs need to be taken so literally as to exclude other chars. I'll reach out to them and ask.

**Comment by lpinca** [comment]
I don't know but I guess there is a reason for it or they would have said to escape all URL unsafe characters (` `, `?`, `#`, `:`, `@`, etc.).

**Comment by jamiemtdwyer** [comment]
Hey guys,

Jamie from Shopify here. I would recommend taking a look at the strategy used in our official OAuth gem for Ruby:

https://github.com/Shopify/omniauth-shopify-oauth2/blob/master/lib/omniauth/strategies/shopify.rb#L67

We replace `&=%` in keys and '&%' in values with their respective URI-encoded values.

Cheers!

**Comment by lpinca** [comment]
@jamiemtdwyer thanks. `shopify-token` does the same thing, see https://github.com/lpinca/shopify-token/blob/0ce4668c9c13a7b8db854966b8665d783255c6a7/index.js#L7-L29 and https://github.com/lpinca/shopify-token/blob/0ce4668c9c13a7b8db854966b8665d783255c6a7/index.js#L113.
