### ISSUE TITLE
Online and Offline Access Tokens

### ISSUE THREAD

**Issue by boxedcode** [lpinca/shopify-token#31]
Hello. I've got a use-case where I require both an offline and online access token. An offline access token for performing background tasks that interact with the Shopify store, and an online access token so I can get details of the logged in user to display within a timeline of events for my Shopify app.

Using your library, what would be the best way of achieving this?

Would you suggest performing 2 Oauth flows, first for the offline access token (save it), then immediately after another for the online access token (save and check expiry on each page load)? Do you have an example of how this would work or is there some other way I have to tackle this requirement?

Thanks.

**Comment by lpinca** [comment]
Yes, you have to do two requests. One for the offline access mode and another for the online access mode.

**Comment by boxedcode** [comment]
> Yes, you have to do two requests. One for the offline access mode and another for the online access mode.

Thanks for confirming the approach. I'll give it a shot and see how I get on.
