### ISSUE TITLE
Implement `timeout` option

### ISSUE THREAD

**Issue by benbuckman** [lpinca/shopify-token#4]
It would be good for the `getAccessToken` method to allow a timeout via an `options.timeout` in the client constructor.

I've tried to do this on a branch of our fork and run into some trouble. (I'll post that momentarily.) Basically the low-level `https.request` interface that the module uses makes timeouts tricky to implement – there is a [`request.setTimeout`](https://nodejs.org/api/http.html#http_request_settimeout_timeout_callback) method but I'm not sure how to fully implement it.

I wonder if this module should switch to using a request abstraction layer. [`shopify-api-node`](https://github.com/microapps/Shopify-api-node), for example, is using the [`got`](https://www.npmjs.com/package/got) module; another obvious one is [`request`](https://github.com/request/request). It would expand the size of this module but also open up a lot of possibilities for request options (such as `timeout`) without having to reinvent the wheel.

**Comment by benbuckman** [comment]
(See PR link above ^^)
Thanks

**Comment by lpinca** [comment]
One option is to use [`timed-out`](https://github.com/floatdrop/timed-out) which is what `got` uses internally.
I didn't want to use `request` or `got` here because this module does literally only one request.

Did you run into a stalled request issue?

**Comment by lpinca** [comment]
> `shopify-api-node`, for example, is using the `got` module

I know, I rewrote that module 😄.
