### ISSUE TITLE
Preflight Cors Fails

### ISSUE THREAD

**Issue by ilrein** [lpinca/shopify-token#9]
Hello,

Thank you for creating this helpful library! I've been tinkering with it in a few tests apps to great success. Alas, I decided to come back to this library and build a new app, but I had unexpected behaviour:

```Fetch API cannot load https://fabrics-2017.myshopify.com/admin/oauth/access_token. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 404. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.```

My application code looks closer to this:...

```const { shopifyToken } = this.props.app;
    const query = queryString.parse(this.props.location.search);
    const checkPassed = shopifyToken.verifyHmac(query);
    console.log(query);
    if (checkPassed) {
      this.setState({
        securityChecksPassed: checkPassed,
      }, () => {
        shopifyToken.getAccessToken(query.shop, query.code)
          .then((token) => {
            console.log('got token', token);
          })
          .catch((err) => {
            console.log('err', err);
          })
```

Is this is an issue on my side? What am I missing?

**Comment by lpinca** [comment]
Hi,
this library can only be used on the server. It doesn't work in the browser.

**Comment by ilrein** [comment]
Ah, thanks for the speedy reply! That was the difference -- this time I wanted to do all the functionality from a static site.

**Comment by AgrawalAman** [comment]
Hi

I am having the same issue with my app, and I implemented this on a node.js server which takes the site address from a get request. Can you tell me how to make it work with AJAX call to an endpoint on the backend? 

thanks
